package channel

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptrace"
	"regexp"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	common2 "github.com/QuantumNous/new-api/common"
	constant2 "github.com/QuantumNous/new-api/constant"
	"github.com/QuantumNous/new-api/logger"
	"github.com/QuantumNous/new-api/relay/common"
	"github.com/QuantumNous/new-api/relay/constant"
	"github.com/QuantumNous/new-api/relay/helper"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/types"

	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

func applyUpstreamContentLength(req *http.Request, info *common.RelayInfo) {
	if info == nil {
		return
	}
	if info.UpstreamRequestBodySize > 0 && req.ContentLength <= 0 {
		req.ContentLength = info.UpstreamRequestBodySize
	}
}

func SetupApiRequestHeader(info *common.RelayInfo, c *gin.Context, req *http.Header) {
	if info.RelayMode == constant.RelayModeAudioTranscription || info.RelayMode == constant.RelayModeAudioTranslation {
		// multipart/form-data
	} else if info.RelayMode == constant.RelayModeRealtime {
		// websocket
	} else {
		req.Set("Content-Type", c.Request.Header.Get("Content-Type"))
		req.Set("Accept", c.Request.Header.Get("Accept"))
		if info.IsStream && c.Request.Header.Get("Accept") == "" {
			req.Set("Accept", "text/event-stream")
		}
	}
}

const clientHeaderPlaceholderPrefix = "{client_header:"

const (
	headerPassthroughAllKey        = "*"
	headerPassthroughRegexPrefix   = "re:"
	headerPassthroughRegexPrefixV2 = "regex:"
)

var passthroughSkipHeaderNamesLower = map[string]struct{}{
	// RFC 7230 hop-by-hop headers.
	"connection":          {},
	"keep-alive":          {},
	"proxy-authenticate":  {},
	"proxy-authorization": {},
	"te":                  {},
	"trailer":             {},
	"transfer-encoding":   {},
	"upgrade":             {},

	"cookie": {},

	// Additional headers that should not be forwarded by name-matching passthrough rules.
	"host":            {},
	"content-length":  {},
	"accept-encoding": {},

	// Do not passthrough credentials by wildcard/regex.
	"authorization":  {},
	"x-api-key":      {},
	"x-goog-api-key": {},

	// WebSocket handshake headers are generated by the client/dialer.
	"sec-websocket-key":        {},
	"sec-websocket-version":    {},
	"sec-websocket-extensions": {},
}

var headerPassthroughRegexCache sync.Map // map[string]*regexp.Regexp

func getHeaderPassthroughRegex(pattern string) (*regexp.Regexp, error) {
	pattern = strings.TrimSpace(pattern)
	if pattern == "" {
		return nil, errors.New("empty regex pattern")
	}
	if v, ok := headerPassthroughRegexCache.Load(pattern); ok {
		if re, ok := v.(*regexp.Regexp); ok {
			return re, nil
		}
		headerPassthroughRegexCache.Delete(pattern)
	}
	compiled, err := regexp.Compile(pattern)
	if err != nil {
		return nil, err
	}
	actual, _ := headerPassthroughRegexCache.LoadOrStore(pattern, compiled)
	if re, ok := actual.(*regexp.Regexp); ok {
		return re, nil
	}
	return compiled, nil
}

func IsHeaderPassthroughRuleKey(key string) bool {
	return isHeaderPassthroughRuleKey(key)
}
func isHeaderPassthroughRuleKey(key string) bool {
	key = strings.TrimSpace(key)
	if key == "" {
		return false
	}
	if key == headerPassthroughAllKey {
		return true
	}
	lower := strings.ToLower(key)
	return strings.HasPrefix(lower, headerPassthroughRegexPrefix) || strings.HasPrefix(lower, headerPassthroughRegexPrefixV2)
}

func shouldSkipPassthroughHeader(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return true
	}
	lower := strings.ToLower(name)
	if _, ok := passthroughSkipHeaderNamesLower[lower]; ok {
		return true
	}
	return false
}

func applyHeaderOverridePlaceholders(template string, c *gin.Context, apiKey string) (string, bool, error) {
	trimmed := strings.TrimSpace(template)
	if strings.HasPrefix(trimmed, clientHeaderPlaceholderPrefix) {
		afterPrefix := trimmed[len(clientHeaderPlaceholderPrefix):]
		end := strings.Index(afterPrefix, "}")
		if end < 0 || end != len(afterPrefix)-1 {
			return "", false, fmt.Errorf("client_header placeholder must be the full value: %q", template)
		}

		name := strings.TrimSpace(afterPrefix[:end])
		if name == "" {
			return "", false, fmt.Errorf("client_header placeholder name is empty: %q", template)
		}
		if c == nil || c.Request == nil {
			return "", false, fmt.Errorf("missing request context for client_header placeholder")
		}
		clientHeaderValue := c.Request.Header.Get(name)
		if strings.TrimSpace(clientHeaderValue) == "" {
			return "", false, nil
		}
		// Do not interpolate {api_key} inside client-supplied content.
		return clientHeaderValue, true, nil
	}

	if strings.Contains(template, "{api_key}") {
		template = strings.ReplaceAll(template, "{api_key}", apiKey)
	}
	if strings.TrimSpace(template) == "" {
		return "", false, nil
	}
	return template, true, nil
}

// processHeaderOverride applies channel header overrides, with placeholder substitution.
// Supported placeholders:
//   - {api_key}: resolved to the channel API key
//   - {client_header:<name>}: resolved to the incoming request header value
//
// Header passthrough rules (keys only; values are ignored):
//   - "*": passthrough all incoming headers by name (excluding unsafe headers)
//   - "re:<regex>" / "regex:<regex>": passthrough headers whose names match the regex (Go regexp)
//
// Passthrough rules are applied first, then normal overrides are applied, so explicit overrides win.
func processHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	headerOverride := make(map[string]string)
	if info == nil {
		return headerOverride, nil
	}

	headerOverrideSource := common.GetEffectiveHeaderOverride(info)

	passAll := false
	var passthroughRegex []*regexp.Regexp
	if !info.IsChannelTest {
		for k := range headerOverrideSource {
			key := strings.TrimSpace(strings.ToLower(k))
			if key == "" {
				continue
			}
			if key == headerPassthroughAllKey {
				passAll = true
				continue
			}

			var pattern string
			switch {
			case strings.HasPrefix(key, headerPassthroughRegexPrefix):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefix):])
			case strings.HasPrefix(key, headerPassthroughRegexPrefixV2):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefixV2):])
			default:
				continue
			}

			if pattern == "" {
				return nil, types.NewError(fmt.Errorf("header passthrough regex pattern is empty: %q", k), types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			compiled, err := getHeaderPassthroughRegex(pattern)
			if err != nil {
				return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			passthroughRegex = append(passthroughRegex, compiled)
		}
	}

	if passAll || len(passthroughRegex) > 0 {
		if c == nil || c.Request == nil {
			return nil, types.NewError(fmt.Errorf("missing request context for header passthrough"), types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		for name := range c.Request.Header {
			if shouldSkipPassthroughHeader(name) {
				continue
			}
			if !passAll {
				matched := false
				for _, re := range passthroughRegex {
					if re.MatchString(name) {
						matched = true
						break
					}
				}
				if !matched {
					continue
				}
			}
			value := strings.TrimSpace(c.Request.Header.Get(name))
			if value == "" {
				continue
			}
			headerOverride[strings.ToLower(strings.TrimSpace(name))] = value
		}
	}

	for k, v := range headerOverrideSource {
		if isHeaderPassthroughRuleKey(k) {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(k))
		if key == "" {
			continue
		}

		str, ok := v.(string)
		if !ok {
			return nil, types.NewError(nil, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if info.IsChannelTest && strings.HasPrefix(strings.TrimSpace(str), clientHeaderPlaceholderPrefix) {
			continue
		}

		value, include, err := applyHeaderOverridePlaceholders(str, c, info.ApiKey)
		if err != nil {
			return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if !include {
			continue
		}

		headerOverride[key] = value
	}
	return headerOverride, nil
}

func ResolveHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	return processHeaderOverride(info, c)
}

func applyHeaderOverrideToRequest(req *http.Request, headerOverride map[string]string) {
	if req == nil {
		return
	}
	for key, value := range headerOverride {
		req.Header.Set(key, value)
		// set Host in req
		if strings.EqualFold(key, "Host") {
			req.Host = value
		}
	}
}

type contextualRequestURLBuilder interface {
	GetRequestURLWithContext(ctx context.Context, info *common.RelayInfo) (string, error)
}

func getRequestURL(a Adaptor, c *gin.Context, info *common.RelayInfo) (string, error) {
	if contextual, ok := a.(contextualRequestURLBuilder); ok && c != nil && c.Request != nil {
		return contextual.GetRequestURLWithContext(c.Request.Context(), info)
	}
	return a.GetRequestURL(info)
}

func DoApiRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := getRequestURL(a, c, info)
	if err != nil {
		if c != nil && c.Request != nil && c.Request.Context().Err() != nil {
			return nil, ClassifyDoRequestError(c, err)
		}
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	if common2.DebugEnabled {
		println("fullRequestURL:", fullRequestURL)
	}
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoFormRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := getRequestURL(a, c, info)
	if err != nil {
		if c != nil && c.Request != nil && c.Request.Context().Err() != nil {
			return nil, ClassifyDoRequestError(c, err)
		}
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	if common2.DebugEnabled {
		println("fullRequestURL:", fullRequestURL)
	}
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	// set form data
	req.Header.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoWssRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*websocket.Conn, error) {
	fullRequestURL, err := getRequestURL(a, c, info)
	if err != nil {
		if c != nil && c.Request != nil && c.Request.Context().Err() != nil {
			return nil, ClassifyDoRequestError(c, err)
		}
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	targetHeader := http.Header{}
	err = a.SetupRequestHeader(c, &targetHeader, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	for key, value := range headerOverride {
		targetHeader.Set(key, value)
	}
	targetHeader.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	common2.ReleaseBodyAdmission(c)
	targetConn, _, err := DialWebSocketContext(c.Request.Context(), fullRequestURL, targetHeader)
	if err != nil {
		if c.Request.Context().Err() != nil {
			return nil, ClassifyDoRequestError(c, err)
		}
		return nil, fmt.Errorf("dial failed to %s: %w", fullRequestURL, err)
	}
	// send request body
	//all, err := io.ReadAll(requestBody)
	//err = service.WssString(c, targetConn, string(all))
	return targetConn, nil
}

// DialWebSocketContext binds an established socket to the original request
// context in addition to using that context for DNS, TCP, and the HTTP upgrade.
// The close watcher must use the original ctx rather than NetDialContext's
// argument: gorilla derives a handshake-only child context and cancels it after
// a successful upgrade, which would immediately close the healthy websocket.
func DialWebSocketContext(ctx context.Context, requestURL string, header http.Header) (*websocket.Conn, *http.Response, error) {
	websocketDialer := *websocket.DefaultDialer
	baseDialContext := websocketDialer.NetDialContext
	if baseDialContext == nil {
		baseDialContext = (&net.Dialer{}).DialContext
	}
	requestContext := ctx
	websocketDialer.NetDialContext = func(dialContext context.Context, network, address string) (net.Conn, error) {
		conn, dialErr := baseDialContext(dialContext, network, address)
		if dialErr != nil {
			return nil, dialErr
		}
		// Bind to the original request context, not gorilla's temporary
		// handshake child context. This interrupts a stalled upgrade and keeps a
		// successfully upgraded connection alive until the request is canceled.
		context.AfterFunc(requestContext, func() {
			_ = conn.Close()
		})
		return conn, nil
	}
	conn, resp, err := websocketDialer.DialContext(ctx, requestURL, header)
	return conn, resp, err
}

func DoRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	return doRequest(c, req, info)
}

const statusClientClosedRequest = 499

// ClassifyDoRequestError distinguishes an inbound cancellation/deadline from
// an upstream transport failure. Client-owned cancellation must never be
// retried or used to disable a healthy channel.
func ClassifyDoRequestError(c *gin.Context, err error) *types.NewAPIError {
	return classifyDoRequestError(c, err, false)
}

type contextCancelReadCloser struct {
	io.ReadCloser
	cancel      context.CancelFunc
	stopInbound func() bool
	once        sync.Once
	closeErr    error
}

func (r *contextCancelReadCloser) Close() error {
	if r == nil {
		return nil
	}
	r.once.Do(func() {
		if r.stopInbound != nil {
			r.stopInbound()
		}
		if r.cancel != nil {
			r.cancel()
		}
		if r.ReadCloser != nil {
			r.closeErr = r.ReadCloser.Close()
		}
	})
	return r.closeErr
}

func classifyDoRequestError(c *gin.Context, err error, requestMayHaveBeenSent bool) *types.NewAPIError {
	if c != nil && c.Request != nil {
		switch requestErr := c.Request.Context().Err(); {
		case errors.Is(requestErr, context.Canceled):
			setRelayCancelOrigin(c, constant2.RelayCancelOriginDownstreamDisconnected)
			return types.NewErrorWithStatusCode(
				errors.New("downstream connection closed before completion"),
				types.ErrorCodeDoRequestFailed,
				statusClientClosedRequest,
				types.ErrOptionWithSkipRetry(),
			)
		case errors.Is(requestErr, context.DeadlineExceeded):
			setRelayCancelOrigin(c, constant2.RelayCancelOriginGatewayDeadline)
			return types.NewErrorWithStatusCode(
				errors.New("request deadline exceeded"),
				types.ErrorCodeDoRequestFailed,
				http.StatusGatewayTimeout,
				types.ErrOptionWithSkipRetry(),
			)
		}
	}
	var netErr net.Error
	if errors.Is(err, context.DeadlineExceeded) || errors.As(err, &netErr) && netErr.Timeout() {
		setRelayCancelOrigin(c, constant2.RelayCancelOriginUpstreamTimeout)
	} else if errors.Is(err, context.Canceled) {
		setRelayCancelOrigin(c, constant2.RelayCancelOriginInternalAbort)
	}

	options := []types.NewAPIErrorOptions{
		types.ErrOptionWithHideErrMsg("upstream error: do request failed"),
	}
	if requestMayHaveBeenSent {
		// Once any request write has completed or failed part-way through, a
		// timeout or connection error cannot prove that the provider rejected the
		// request. Retrying could duplicate a generation, task, tool call, or bill.
		options = append(options, types.ErrOptionWithSkipRetry(), types.ErrOptionWithChannelPenalty())
		if errors.Is(err, context.DeadlineExceeded) || errors.As(err, &netErr) && netErr.Timeout() {
			return types.NewErrorWithStatusCode(
				errors.New("upstream response headers timed out before the first valid event"),
				types.ErrorCodeUpstreamFirstEventTimeout,
				http.StatusGatewayTimeout,
				options...,
			)
		}
	}
	return types.NewError(err, types.ErrorCodeDoRequestFailed, options...)
}

func firstValidEventBudgetError(c *gin.Context, requestMayHaveBeenSent bool) *types.NewAPIError {
	setRelayCancelOrigin(c, constant2.RelayCancelOriginGatewayDeadline)
	options := []types.NewAPIErrorOptions{types.ErrOptionWithSkipRetry()}
	if requestMayHaveBeenSent {
		options = append(options, types.ErrOptionWithChannelPenalty())
	}
	return types.NewErrorWithStatusCode(
		errors.New("request-wide first valid event budget exhausted"),
		types.ErrorCodeUpstreamFirstEventTimeout,
		http.StatusGatewayTimeout,
		options...,
	)
}

func setRelayCancelOrigin(c *gin.Context, origin string) {
	if c == nil || strings.TrimSpace(origin) == "" {
		return
	}
	common2.SetContextKey(c, constant2.ContextKeyRelayCancelOrigin, origin)
}

// startPreResponseHeartbeat keeps streaming clients and transit proxies alive
// while the upstream is still waiting to return response headers. It starts
// only after a short compatibility delay so fast upstream failures can still
// be returned with their original HTTP status. Stopping waits for the writer
// goroutine, preventing it from racing the downstream stream handler.
func startPreResponseHeartbeat(c *gin.Context, info *common.RelayInfo) func() {
	interval := common2.RelayPreFirstEventHeartbeatInterval
	if c == nil || c.Request == nil || c.Writer == nil || info == nil || !info.IsStream || info.DisablePing || interval <= 0 {
		return func() {}
	}

	ctx, cancel := context.WithCancel(c.Request.Context())
	done := make(chan struct{})
	go func() {
		defer func() {
			if r := recover(); r != nil {
				logger.LogError(c, fmt.Sprintf("pre-response heartbeat panic: %v", r))
			}
			close(done)
		}()
		ticker := time.NewTicker(interval)
		defer ticker.Stop()
		for {
			select {
			case <-ticker.C:
				helper.ExtendWriteDeadline(c)
				if err := helper.PingData(c); err != nil {
					logger.LogDebug(c, "pre-response heartbeat stopped: "+err.Error())
					return
				}
			case <-ctx.Done():
				return
			}
		}
	}()

	return func() {
		cancel()
		<-done
	}
}

func doRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	// Some provider adaptors build requests with their own timeout context before
	// delegating here. Preserve that deadline/value context while also binding it
	// to the inbound client lifetime. The combined context stays alive until the
	// response body is closed; canceling it on return from client.Do would truncate
	// every stream immediately after response headers.
	var combinedCancel context.CancelFunc
	var stopInbound func() bool
	if req != nil && c != nil && c.Request != nil {
		// Carry the validated edge request ID through NewAPI and compatible
		// upstream relays (notably CPA) without overwriting an adaptor-provided
		// value. Providers that do not use this private X- header ignore it.
		if requestID := c.GetString(common2.RequestIdKey); requestID != "" {
			if req.Header.Get(common2.RequestIdKey) == "" {
				req.Header.Set(common2.RequestIdKey, requestID)
			}
			if req.Header.Get("X-Request-Id") == "" {
				req.Header.Set("X-Request-Id", requestID)
			}
		}
		combinedCtx, cancel := context.WithCancel(req.Context())
		combinedCancel = cancel
		stopInbound = context.AfterFunc(c.Request.Context(), cancel)
		req = req.WithContext(combinedCtx)
	}

	var client *http.Client
	var err error
	if info.ChannelSetting.Proxy != "" {
		client, err = service.GetHttpClientWithProxy(info.ChannelSetting.Proxy)
		if err != nil {
			return nil, fmt.Errorf("new proxy http client failed: %w", err)
		}
	} else {
		client = service.GetHttpClient()
	}

	// Do not set downstream SSE headers or write heartbeat bytes before the
	// upstream produces a valid event. Either action can commit a downstream 200
	// and hide an upstream first-event timeout from the controller.

	var requestMayHaveBeenSent atomic.Bool
	unsafeToReplay := !isReplaySafeMethod(req.Method)
	trace := &httptrace.ClientTrace{
		GotConn: func(httptrace.GotConnInfo) {
			common2.SetContextKey(c, constant2.ContextKeyRelayConnectedUpstream, true)
		},
		WroteRequest: func(httptrace.WroteRequestInfo) {
			common2.SetContextKey(c, constant2.ContextKeyRelayRequestWritten, true)
			requestMayHaveBeenSent.Store(true)
			if unsafeToReplay {
				info.MarkUpstreamRequestMayHaveBeenAccepted()
			}
		},
	}
	req = req.WithContext(httptrace.WithClientTrace(req.Context(), trace))

	// The absolute pre-output budget is implemented with a stoppable cancel
	// timer rather than a Context deadline. Once response headers arrive the
	// timer is disarmed, allowing a healthy SSE body to continue indefinitely;
	// the scanner then uses the same deadline only until its first valid event.
	var budgetState atomic.Uint32 // 0=armed, 1=disarmed, 2=expired
	var budgetTimer *time.Timer
	if combinedCancel != nil {
		if remaining, limited := info.RemainingFirstValidEventBudget(); limited {
			if remaining <= 0 {
				if stopInbound != nil {
					stopInbound()
				}
				combinedCancel()
				return nil, firstValidEventBudgetError(c, false)
			}
			budgetTimer = time.AfterFunc(remaining, func() {
				if budgetState.CompareAndSwap(0, 2) {
					combinedCancel()
				}
			})
		}
	}

	// Task and provider-specific paths may not pass through controller.Relay's
	// validated DTO boundary. Release the parsing lease at the final outbound
	// boundary as an idempotent fallback, before waiting on response headers or
	// a potentially long-lived stream.
	common2.ReleaseBodyAdmission(c)
	stopPreResponseHeartbeat := startPreResponseHeartbeat(c, info)
	resp, err := client.Do(req)
	stopPreResponseHeartbeat()
	if budgetTimer != nil {
		budgetState.CompareAndSwap(0, 1)
		budgetTimer.Stop()
	}
	requestReachedUpstream := requestMayHaveBeenSent.Load() || resp != nil
	unsafeRequestReachedUpstream := unsafeToReplay && requestReachedUpstream
	if unsafeRequestReachedUpstream {
		info.MarkUpstreamRequestMayHaveBeenAccepted()
	}
	if err != nil {
		if stopInbound != nil {
			stopInbound()
		}
		if combinedCancel != nil {
			combinedCancel()
		}
		if budgetState.Load() == 2 && (c == nil || c.Request == nil || c.Request.Context().Err() == nil) {
			if resp != nil && resp.Body != nil {
				_ = resp.Body.Close()
			}
			return nil, firstValidEventBudgetError(c, unsafeRequestReachedUpstream)
		}
		classifiedErr := classifyDoRequestError(c, err, unsafeRequestReachedUpstream)
		if !types.IsSkipRetryError(classifiedErr) {
			logger.LogError(c, "do request failed: "+err.Error())
		}
		return nil, classifiedErr
	}
	if resp == nil {
		if stopInbound != nil {
			stopInbound()
		}
		if combinedCancel != nil {
			combinedCancel()
		}
		return nil, errors.New("resp is nil")
	}
	common2.SetContextKey(c, constant2.ContextKeyRelayResponseHeaders, true)
	if budgetState.Load() == 2 {
		if resp.Body != nil {
			_ = resp.Body.Close()
		}
		if stopInbound != nil {
			stopInbound()
		}
		if combinedCancel != nil {
			combinedCancel()
		}
		return nil, firstValidEventBudgetError(c, unsafeRequestReachedUpstream)
	}
	if combinedCancel != nil {
		if resp.Body == nil {
			if stopInbound != nil {
				stopInbound()
			}
			combinedCancel()
		} else {
			resp.Body = &contextCancelReadCloser{
				ReadCloser:  resp.Body,
				cancel:      combinedCancel,
				stopInbound: stopInbound,
			}
		}
	}

	if upID := firstNonEmptyHeader(resp.Header, common2.RequestIdKey, "X-Request-Id", "OpenAI-Request-ID", "Request-ID"); upID != "" {
		c.Set(common2.UpstreamRequestIdKey, upID)
	}

	if req.Body != nil {
		_ = req.Body.Close()
	}
	if c != nil && c.Request != nil && c.Request.Body != nil {
		_ = c.Request.Body.Close()
	}
	return resp, nil
}

func firstNonEmptyHeader(header http.Header, names ...string) string {
	for _, name := range names {
		if value := strings.TrimSpace(header.Get(name)); value != "" {
			return value
		}
	}
	return ""
}

func isReplaySafeMethod(method string) bool {
	switch strings.ToUpper(strings.TrimSpace(method)) {
	case http.MethodGet, http.MethodHead, http.MethodOptions, http.MethodTrace:
		return true
	default:
		return false
	}
}

func DoTaskApiRequest(a TaskAdaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.BuildRequestURL(info)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	err = a.BuildRequestHeader(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}
