package channel

import (
	"context"
	"crypto/tls"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptrace"
	"net/url"
	"regexp"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	common2 "github.com/QuantumNous/new-api/common"
	constant2 "github.com/QuantumNous/new-api/constant"
	"github.com/QuantumNous/new-api/logger"
	"github.com/QuantumNous/new-api/relay/common"
	"github.com/QuantumNous/new-api/relay/constant"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/types"

	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

func applyUpstreamContentLength(req *http.Request, info *common.RelayInfo) {
	if info == nil {
		return
	}
	if info.UpstreamRequestBodySize > 0 && req.ContentLength <= 0 {
		req.ContentLength = info.UpstreamRequestBodySize
	}
}

func SetupApiRequestHeader(info *common.RelayInfo, c *gin.Context, req *http.Header) {
	if info.RelayMode == constant.RelayModeAudioTranscription || info.RelayMode == constant.RelayModeAudioTranslation {
		// multipart/form-data
	} else if info.RelayMode == constant.RelayModeRealtime {
		// websocket
	} else {
		req.Set("Content-Type", c.Request.Header.Get("Content-Type"))
		req.Set("Accept", c.Request.Header.Get("Accept"))
		if info.IsStream && c.Request.Header.Get("Accept") == "" {
			req.Set("Accept", "text/event-stream")
		}
	}
}

const clientHeaderPlaceholderPrefix = "{client_header:"

const (
	headerPassthroughAllKey        = "*"
	headerPassthroughRegexPrefix   = "re:"
	headerPassthroughRegexPrefixV2 = "regex:"
)

var passthroughSkipHeaderNamesLower = map[string]struct{}{
	// RFC 7230 hop-by-hop headers.
	"connection":          {},
	"keep-alive":          {},
	"proxy-authenticate":  {},
	"proxy-authorization": {},
	"te":                  {},
	"trailer":             {},
	"transfer-encoding":   {},
	"upgrade":             {},

	"cookie": {},

	// Additional headers that should not be forwarded by name-matching passthrough rules.
	"host":            {},
	"content-length":  {},
	"accept-encoding": {},

	// Do not passthrough credentials by wildcard/regex.
	"authorization":  {},
	"x-api-key":      {},
	"x-goog-api-key": {},

	// WebSocket handshake headers are generated by the client/dialer.
	"sec-websocket-key":        {},
	"sec-websocket-version":    {},
	"sec-websocket-extensions": {},
}

var headerPassthroughRegexCache sync.Map // map[string]*regexp.Regexp

func getHeaderPassthroughRegex(pattern string) (*regexp.Regexp, error) {
	pattern = strings.TrimSpace(pattern)
	if pattern == "" {
		return nil, errors.New("empty regex pattern")
	}
	if v, ok := headerPassthroughRegexCache.Load(pattern); ok {
		if re, ok := v.(*regexp.Regexp); ok {
			return re, nil
		}
		headerPassthroughRegexCache.Delete(pattern)
	}
	compiled, err := regexp.Compile(pattern)
	if err != nil {
		return nil, err
	}
	actual, _ := headerPassthroughRegexCache.LoadOrStore(pattern, compiled)
	if re, ok := actual.(*regexp.Regexp); ok {
		return re, nil
	}
	return compiled, nil
}

func IsHeaderPassthroughRuleKey(key string) bool {
	return isHeaderPassthroughRuleKey(key)
}
func isHeaderPassthroughRuleKey(key string) bool {
	key = strings.TrimSpace(key)
	if key == "" {
		return false
	}
	if key == headerPassthroughAllKey {
		return true
	}
	lower := strings.ToLower(key)
	return strings.HasPrefix(lower, headerPassthroughRegexPrefix) || strings.HasPrefix(lower, headerPassthroughRegexPrefixV2)
}

func shouldSkipPassthroughHeader(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return true
	}
	lower := strings.ToLower(name)
	if _, ok := passthroughSkipHeaderNamesLower[lower]; ok {
		return true
	}
	return false
}

func applyHeaderOverridePlaceholders(template string, c *gin.Context, apiKey string) (string, bool, error) {
	trimmed := strings.TrimSpace(template)
	if strings.HasPrefix(trimmed, clientHeaderPlaceholderPrefix) {
		afterPrefix := trimmed[len(clientHeaderPlaceholderPrefix):]
		end := strings.Index(afterPrefix, "}")
		if end < 0 || end != len(afterPrefix)-1 {
			return "", false, fmt.Errorf("client_header placeholder must be the full value: %q", template)
		}

		name := strings.TrimSpace(afterPrefix[:end])
		if name == "" {
			return "", false, fmt.Errorf("client_header placeholder name is empty: %q", template)
		}
		if c == nil || c.Request == nil {
			return "", false, fmt.Errorf("missing request context for client_header placeholder")
		}
		clientHeaderValue := c.Request.Header.Get(name)
		if strings.TrimSpace(clientHeaderValue) == "" {
			return "", false, nil
		}
		// Do not interpolate {api_key} inside client-supplied content.
		return clientHeaderValue, true, nil
	}

	if strings.Contains(template, "{api_key}") {
		template = strings.ReplaceAll(template, "{api_key}", apiKey)
	}
	if strings.TrimSpace(template) == "" {
		return "", false, nil
	}
	return template, true, nil
}

// processHeaderOverride applies channel header overrides, with placeholder substitution.
// Supported placeholders:
//   - {api_key}: resolved to the channel API key
//   - {client_header:<name>}: resolved to the incoming request header value
//
// Header passthrough rules (keys only; values are ignored):
//   - "*": passthrough all incoming headers by name (excluding unsafe headers)
//   - "re:<regex>" / "regex:<regex>": passthrough headers whose names match the regex (Go regexp)
//
// Passthrough rules are applied first, then normal overrides are applied, so explicit overrides win.
func processHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	headerOverride := make(map[string]string)
	if info == nil {
		return headerOverride, nil
	}

	headerOverrideSource := common.GetEffectiveHeaderOverride(info)

	passAll := false
	var passthroughRegex []*regexp.Regexp
	if !info.IsChannelTest {
		for k := range headerOverrideSource {
			key := strings.TrimSpace(strings.ToLower(k))
			if key == "" {
				continue
			}
			if key == headerPassthroughAllKey {
				passAll = true
				continue
			}

			var pattern string
			switch {
			case strings.HasPrefix(key, headerPassthroughRegexPrefix):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefix):])
			case strings.HasPrefix(key, headerPassthroughRegexPrefixV2):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefixV2):])
			default:
				continue
			}

			if pattern == "" {
				return nil, types.NewError(fmt.Errorf("header passthrough regex pattern is empty: %q", k), types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			compiled, err := getHeaderPassthroughRegex(pattern)
			if err != nil {
				return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			passthroughRegex = append(passthroughRegex, compiled)
		}
	}

	if passAll || len(passthroughRegex) > 0 {
		if c == nil || c.Request == nil {
			return nil, types.NewError(fmt.Errorf("missing request context for header passthrough"), types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		for name := range c.Request.Header {
			if shouldSkipPassthroughHeader(name) {
				continue
			}
			if !passAll {
				matched := false
				for _, re := range passthroughRegex {
					if re.MatchString(name) {
						matched = true
						break
					}
				}
				if !matched {
					continue
				}
			}
			value := strings.TrimSpace(c.Request.Header.Get(name))
			if value == "" {
				continue
			}
			headerOverride[strings.ToLower(strings.TrimSpace(name))] = value
		}
	}

	for k, v := range headerOverrideSource {
		if isHeaderPassthroughRuleKey(k) {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(k))
		if key == "" {
			continue
		}

		str, ok := v.(string)
		if !ok {
			return nil, types.NewError(nil, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if info.IsChannelTest && strings.HasPrefix(strings.TrimSpace(str), clientHeaderPlaceholderPrefix) {
			continue
		}

		value, include, err := applyHeaderOverridePlaceholders(str, c, info.ApiKey)
		if err != nil {
			return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if !include {
			continue
		}

		headerOverride[key] = value
	}
	return headerOverride, nil
}

func ResolveHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	return processHeaderOverride(info, c)
}

func applyHeaderOverrideToRequest(req *http.Request, headerOverride map[string]string) {
	if req == nil {
		return
	}
	for key, value := range headerOverride {
		req.Header.Set(key, value)
		// set Host in req
		if strings.EqualFold(key, "Host") {
			req.Host = value
		}
	}
}

type contextualRequestURLBuilder interface {
	GetRequestURLWithContext(ctx context.Context, info *common.RelayInfo) (string, error)
}

func getRequestURL(a Adaptor, c *gin.Context, info *common.RelayInfo) (string, error) {
	if contextual, ok := a.(contextualRequestURLBuilder); ok && c != nil && c.Request != nil {
		return contextual.GetRequestURLWithContext(c.Request.Context(), info)
	}
	return a.GetRequestURL(info)
}

func DoApiRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := getRequestURL(a, c, info)
	if err != nil {
		if c != nil && c.Request != nil && c.Request.Context().Err() != nil {
			return nil, ClassifyDoRequestError(c, err)
		}
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	if common2.DebugEnabled {
		println("fullRequestURL:", fullRequestURL)
	}
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoFormRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := getRequestURL(a, c, info)
	if err != nil {
		if c != nil && c.Request != nil && c.Request.Context().Err() != nil {
			return nil, ClassifyDoRequestError(c, err)
		}
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	if common2.DebugEnabled {
		println("fullRequestURL:", fullRequestURL)
	}
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	// set form data
	req.Header.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoWssRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*websocket.Conn, error) {
	common2.ResetRelayAttemptTimeoutContext(c)
	fullRequestURL, err := getRequestURL(a, c, info)
	if err != nil {
		if c != nil && c.Request != nil && c.Request.Context().Err() != nil {
			return nil, ClassifyDoRequestError(c, err)
		}
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	targetHeader := http.Header{}
	err = a.SetupRequestHeader(c, &targetHeader, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	for key, value := range headerOverride {
		targetHeader.Set(key, value)
	}
	targetHeader.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	common2.ReleaseBodyAdmission(c)
	targetConn, targetResp, err := DialWebSocketContext(c.Request.Context(), fullRequestURL, targetHeader)
	if err != nil {
		return nil, handleWebSocketHandshakeFailure(c, fullRequestURL, targetResp, err)
	}
	// send request body
	//all, err := io.ReadAll(requestBody)
	//err = service.WssString(c, targetConn, string(all))
	return targetConn, nil
}

func handleWebSocketHandshakeFailure(c *gin.Context, requestURL string, resp *http.Response, err error) error {
	service.CloseResponseBodyGracefully(resp)
	if classifiedErr := ClassifyWebSocketHandshakeError(c, err); classifiedErr != nil {
		return classifiedErr
	}
	return fmt.Errorf("dial failed to %s: %w", requestURL, err)
}

// DialWebSocketContext binds an established socket to the original request
// context in addition to using that context for DNS, TCP, and the HTTP upgrade.
// The close watcher must use the original ctx rather than NetDialContext's
// argument: gorilla derives a handshake-only child context and cancels it after
// a successful upgrade, which would immediately close the healthy websocket.
type relayWebSocketPhaseTimeoutError struct {
	phase          string
	timeoutSeconds int
	err            error
}

func (e *relayWebSocketPhaseTimeoutError) Error() string { return e.err.Error() }
func (e *relayWebSocketPhaseTimeoutError) Unwrap() error { return e.err }
func (e *relayWebSocketPhaseTimeoutError) Timeout() bool { return true }
func (e *relayWebSocketPhaseTimeoutError) Temporary() bool {
	return true
}

func phaseTimeoutSeconds(timeout time.Duration) int {
	if timeout <= 0 {
		return 0
	}
	return int((timeout + time.Second - 1) / time.Second)
}

func withRelayWebSocketDialTimeout(baseDialContext func(context.Context, string, string) (net.Conn, error), timeout time.Duration) func(context.Context, string, string) (net.Conn, error) {
	if timeout <= 0 {
		return baseDialContext
	}
	return func(ctx context.Context, network, address string) (net.Conn, error) {
		dialCtx, cancel := context.WithTimeout(ctx, timeout)
		defer cancel()
		conn, err := baseDialContext(dialCtx, network, address)
		if err != nil && errors.Is(dialCtx.Err(), context.DeadlineExceeded) && ctx.Err() == nil {
			return nil, &relayWebSocketPhaseTimeoutError{
				phase:          "connect",
				timeoutSeconds: phaseTimeoutSeconds(timeout),
				err:            err,
			}
		}
		return conn, err
	}
}

func withRelayWebSocketTLSHandshakeTimeout(
	baseDialContext func(context.Context, string, string) (net.Conn, error),
	tlsConfig *tls.Config,
	timeout time.Duration,
) func(context.Context, string, string) (net.Conn, error) {
	return func(ctx context.Context, network, address string) (net.Conn, error) {
		rawConn, err := baseDialContext(ctx, network, address)
		if err != nil {
			return nil, err
		}
		config := &tls.Config{}
		if tlsConfig != nil {
			config = tlsConfig.Clone()
		}
		if config.ServerName == "" {
			host, _, splitErr := net.SplitHostPort(address)
			if splitErr != nil {
				host = address
			}
			config.ServerName = strings.Trim(host, "[]")
		}
		tlsConn := tls.Client(rawConn, config)
		handshakeCtx := ctx
		cancel := func() {}
		if timeout > 0 {
			handshakeCtx, cancel = context.WithTimeout(ctx, timeout)
		}
		defer cancel()
		if err = tlsConn.HandshakeContext(handshakeCtx); err != nil {
			_ = rawConn.Close()
			if errors.Is(handshakeCtx.Err(), context.DeadlineExceeded) && ctx.Err() == nil {
				return nil, &relayWebSocketPhaseTimeoutError{
					phase:          "tls_handshake",
					timeoutSeconds: phaseTimeoutSeconds(timeout),
					err:            err,
				}
			}
			return nil, err
		}
		return tlsConn, nil
	}
}

func newRelayWebSocketDialer() websocket.Dialer {
	websocketDialer := *websocket.DefaultDialer
	// gorilla's DefaultDialer carries a hidden 45s handshake timeout. Use the
	// same explicit response-header phase budget as HTTP relay requests so a
	// WebSocket upgrade does not fail early with an unrelated 500. A configured
	// value of zero deliberately disables the local handshake deadline.
	websocketDialer.HandshakeTimeout = time.Duration(common2.RelayResponseHeaderTimeout) * time.Second
	baseDialContext := websocketDialer.NetDialContext
	if baseDialContext == nil {
		baseDialContext = (&net.Dialer{KeepAlive: 30 * time.Second}).DialContext
	}
	websocketDialer.NetDialContext = withRelayWebSocketDialTimeout(
		baseDialContext,
		time.Duration(common2.RelayDialTimeout)*time.Second,
	)
	if common2.TLSInsecureSkipVerify {
		websocketDialer.TLSClientConfig = common2.InsecureTLSConfig.Clone()
	}
	return websocketDialer
}

func configureDirectRelayWebSocketTLS(ctx context.Context, requestURL string, websocketDialer *websocket.Dialer) {
	if websocketDialer == nil {
		return
	}
	parsedURL, err := url.Parse(requestURL)
	if err != nil || !strings.EqualFold(parsedURL.Scheme, "wss") {
		return
	}
	proxyURL := *parsedURL
	proxyURL.Scheme = "https"
	if websocketDialer.Proxy != nil {
		proxyRequest := &http.Request{Method: http.MethodGet, URL: &proxyURL, Header: make(http.Header)}
		proxyRequest = proxyRequest.WithContext(ctx)
		resolvedProxy, proxyErr := websocketDialer.Proxy(proxyRequest)
		if proxyErr != nil || resolvedProxy != nil {
			// gorilla owns CONNECT proxy negotiation. Its aggregate upgrade budget
			// remains the fallback because NetDialTLSContext cannot safely wrap the
			// post-CONNECT TLS phase without reimplementing the proxy handshake.
			return
		}
		websocketDialer.Proxy = nil
	}
	websocketDialer.NetDialTLSContext = withRelayWebSocketTLSHandshakeTimeout(
		websocketDialer.NetDialContext,
		websocketDialer.TLSClientConfig,
		time.Duration(common2.RelayTLSHandshakeTimeout)*time.Second,
	)
}

func DialWebSocketContext(ctx context.Context, requestURL string, header http.Header) (*websocket.Conn, *http.Response, error) {
	return dialWebSocketContext(ctx, ctx, requestURL, header)
}

// DialWebSocketContextWithHandshakeContext lets a provider impose a shorter
// pre-first-event/upgrade budget without binding a successfully upgraded
// socket to that temporary context. The socket lifetime always follows
// requestCtx; only DNS, connect, TLS, and the HTTP upgrade use handshakeCtx.
func DialWebSocketContextWithHandshakeContext(requestCtx context.Context, handshakeCtx context.Context, requestURL string, header http.Header) (*websocket.Conn, *http.Response, error) {
	return dialWebSocketContext(requestCtx, handshakeCtx, requestURL, header)
}

func dialWebSocketContext(requestCtx context.Context, handshakeCtx context.Context, requestURL string, header http.Header) (*websocket.Conn, *http.Response, error) {
	if requestCtx == nil {
		requestCtx = context.Background()
	}
	if handshakeCtx == nil {
		handshakeCtx = requestCtx
	}
	websocketDialer := newRelayWebSocketDialer()
	baseDialContext := websocketDialer.NetDialContext
	websocketDialer.NetDialContext = func(dialContext context.Context, network, address string) (net.Conn, error) {
		conn, dialErr := baseDialContext(dialContext, network, address)
		if dialErr != nil {
			return nil, dialErr
		}
		// Bind to the original request context, not gorilla's temporary
		// handshake child context. This interrupts a stalled upgrade and keeps a
		// successfully upgraded connection alive until the request is canceled.
		context.AfterFunc(requestCtx, func() {
			_ = conn.Close()
		})
		return conn, nil
	}
	// gorilla prefers NetDialTLSContext for wss://. Configure it only after the
	// request-lifetime watcher wraps NetDialContext so direct TLS sockets cannot
	// bypass cancellation after a successful upgrade.
	configureDirectRelayWebSocketTLS(handshakeCtx, requestURL, &websocketDialer)
	conn, resp, err := websocketDialer.DialContext(handshakeCtx, requestURL, header)
	return conn, resp, err
}

func DoRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	return doRequest(c, req, info)
}

const statusClientClosedRequest = 499

// ClassifyDoRequestError distinguishes an inbound cancellation/deadline from
// an upstream transport failure. Client-owned cancellation must never be
// retried or used to disable a healthy channel.
func ClassifyDoRequestError(c *gin.Context, err error) *types.NewAPIError {
	return classifyDoRequestError(c, err, false)
}

const requestDeadlineClassificationGrace = 5 * time.Millisecond

// requestContextError also recognizes a deadline that has just elapsed before
// context.Err() becomes observable. Network pollers and context timers can wake
// on the same absolute deadline; without this check a caller-owned deadline can
// race into an upstream timeout classification and incorrectly penalize a
// channel.
func requestContextError(c *gin.Context) error {
	if c == nil || c.Request == nil {
		return nil
	}
	ctx := c.Request.Context()
	if err := ctx.Err(); err != nil {
		return err
	}
	if deadline, ok := ctx.Deadline(); ok && time.Until(deadline) <= requestDeadlineClassificationGrace {
		return context.DeadlineExceeded
	}
	return nil
}

// ClassifyWebSocketHandshakeError maps a locally timed-out upstream HTTP
// upgrade onto the same typed 504 used by ordinary response-header waits.
// The upgrade request has already crossed the network by this point, so keep
// the conservative no-replay and channel-penalty boundary. Caller-owned
// cancellation/deadlines retain their existing 499/504 semantics and never
// penalize the selected channel.
func ClassifyWebSocketHandshakeError(c *gin.Context, err error) *types.NewAPIError {
	if requestContextError(c) != nil {
		return classifyDoRequestError(c, err, false)
	}
	var netErr net.Error
	if !errors.Is(err, context.DeadlineExceeded) && (!errors.As(err, &netErr) || !netErr.Timeout()) {
		return nil
	}
	phase := "response_headers"
	timeoutSeconds := common2.RelayResponseHeaderTimeout
	var phaseErr *relayWebSocketPhaseTimeoutError
	if errors.As(err, &phaseErr) {
		phase = phaseErr.phase
		timeoutSeconds = phaseErr.timeoutSeconds
	}
	common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutPhase, phase)
	common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutSeconds, timeoutSeconds)
	if phase == "connect" || phase == "tls_handshake" {
		// No WebSocket upgrade request, model payload, or generation has crossed
		// the connection yet. Another channel remains safe to try.
		return classifyDoRequestError(c, err, false)
	}
	// The HTTP upgrade reached the selected channel, so record a channel
	// penalty, but do not suppress retry: the model payload is sent only after a
	// successful upgrade and cannot have been accepted at this point.
	setRelayCancelOrigin(c, constant2.RelayCancelOriginUpstreamTimeout)
	return types.NewErrorWithStatusCode(
		errors.New("upstream WebSocket response headers timed out"),
		types.ErrorCodeUpstreamResponseHeaderTimeout,
		http.StatusGatewayTimeout,
		types.ErrOptionWithChannelPenalty(),
	)
}

type contextCancelReadCloser struct {
	io.ReadCloser
	cancel                       context.CancelFunc
	stopInbound                  func() bool
	requestCtx                   context.Context
	ginCtx                       *gin.Context
	nonStreamTimer               *cancelPhaseTimer
	stopNonStreamObserver        func() bool
	nonStreamTimeout             int
	streamErrorBodyTimer         *cancelPhaseTimer
	unsafeRequestReachedUpstream bool
	once                         sync.Once
	closeErr                     error
}

func (r *contextCancelReadCloser) Read(p []byte) (int, error) {
	if r == nil || r.ReadCloser == nil {
		return 0, io.EOF
	}
	n, err := r.ReadCloser.Read(p)
	if err == nil {
		return n, nil
	}
	// A natural EOF is a completed non-stream response. Disarm the timer before
	// looking at the context so an EOF racing the deadline is not rewritten as a
	// false timeout.
	if errors.Is(err, io.EOF) {
		if r.stopNonStreamObserver != nil {
			r.stopNonStreamObserver()
		}
		if r.nonStreamTimer != nil {
			r.nonStreamTimer.Disarm()
		}
		if r.streamErrorBodyTimer != nil {
			r.streamErrorBodyTimer.Disarm()
		}
		return n, err
	}
	if r.nonStreamTimer != nil && r.nonStreamTimer.Expired() {
		return n, nonStreamTotalTimeoutError(r.ginCtx, r.nonStreamTimeout, r.unsafeRequestReachedUpstream)
	}
	if r.streamErrorBodyTimer != nil && r.streamErrorBodyTimer.Expired() {
		return n, firstValidEventBudgetError(r.ginCtx, r.unsafeRequestReachedUpstream)
	}
	// Preserve downstream cancellation/deadline semantics while a response body
	// is being read. Returning a typed error here prevents provider adaptors from
	// turning a gateway deadline into read_response_body_failed/500.
	if r.requestCtx != nil && r.requestCtx.Err() != nil {
		return n, classifyResponseBodyContextError(r.ginCtx, r.requestCtx.Err(), r.unsafeRequestReachedUpstream)
	}
	return n, err
}

func (r *contextCancelReadCloser) Close() error {
	if r == nil {
		return nil
	}
	r.once.Do(func() {
		if r.stopNonStreamObserver != nil {
			r.stopNonStreamObserver()
		}
		if r.nonStreamTimer != nil {
			r.nonStreamTimer.Disarm()
		}
		if r.streamErrorBodyTimer != nil {
			r.streamErrorBodyTimer.Disarm()
		}
		if r.stopInbound != nil {
			r.stopInbound()
		}
		if r.cancel != nil {
			r.cancel()
		}
		if r.ReadCloser != nil {
			r.closeErr = r.ReadCloser.Close()
		}
	})
	return r.closeErr
}

const (
	phaseTimerArmed uint32 = iota
	phaseTimerDisarmed
	phaseTimerExpired
)

// cancelPhaseTimer records which local phase budget canceled a shared request
// context. A plain context deadline cannot distinguish response-header,
// first-event, and full non-stream budgets when more than one is active.
type cancelPhaseTimer struct {
	state atomic.Uint32
	timer *time.Timer
}

func newCancelPhaseTimer(duration time.Duration, cancel context.CancelFunc) *cancelPhaseTimer {
	if duration <= 0 || cancel == nil {
		return nil
	}
	phaseTimer := &cancelPhaseTimer{}
	phaseTimer.timer = time.AfterFunc(duration, func() {
		if phaseTimer.state.CompareAndSwap(phaseTimerArmed, phaseTimerExpired) {
			cancel()
		}
	})
	return phaseTimer
}

func (t *cancelPhaseTimer) Disarm() bool {
	if t == nil {
		return true
	}
	disarmed := t.state.CompareAndSwap(phaseTimerArmed, phaseTimerDisarmed)
	if t.timer != nil {
		t.timer.Stop()
	}
	return disarmed || t.state.Load() == phaseTimerDisarmed
}

func (t *cancelPhaseTimer) Expired() bool {
	return t != nil && t.state.Load() == phaseTimerExpired
}

func classifyResponseBodyContextError(c *gin.Context, requestErr error, requestMayHaveBeenSent bool) *types.NewAPIError {
	if c != nil && c.Request != nil && c.Request.Context().Err() != nil {
		return classifyDoRequestError(c, requestErr, requestMayHaveBeenSent)
	}
	options := []types.NewAPIErrorOptions{types.ErrOptionWithSkipRetry()}
	if requestMayHaveBeenSent {
		options = append(options, types.ErrOptionWithChannelPenalty())
	}
	if errors.Is(requestErr, context.DeadlineExceeded) {
		setRelayCancelOrigin(c, constant2.RelayCancelOriginGatewayDeadline)
		common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutPhase, "response_body_context")
		return types.NewErrorWithStatusCode(
			errors.New("response body context deadline exceeded"),
			types.ErrorCodeDoRequestFailed,
			http.StatusGatewayTimeout,
			options...,
		)
	}
	setRelayCancelOrigin(c, constant2.RelayCancelOriginInternalAbort)
	return types.NewError(requestErr, types.ErrorCodeDoRequestFailed, options...)
}

func classifyDoRequestError(c *gin.Context, err error, requestMayHaveBeenSent bool) *types.NewAPIError {
	if c != nil && c.Request != nil {
		switch requestErr := requestContextError(c); {
		case errors.Is(requestErr, context.Canceled):
			setRelayCancelOrigin(c, constant2.RelayCancelOriginDownstreamDisconnected)
			return types.NewErrorWithStatusCode(
				errors.New("downstream connection closed before completion"),
				types.ErrorCodeDoRequestFailed,
				statusClientClosedRequest,
				types.ErrOptionWithSkipRetry(),
			)
		case errors.Is(requestErr, context.DeadlineExceeded):
			setRelayCancelOrigin(c, constant2.RelayCancelOriginGatewayDeadline)
			return types.NewErrorWithStatusCode(
				errors.New("request deadline exceeded"),
				types.ErrorCodeDoRequestFailed,
				http.StatusGatewayTimeout,
				types.ErrOptionWithSkipRetry(),
			)
		}
	}
	var netErr net.Error
	if errors.Is(err, context.DeadlineExceeded) || errors.As(err, &netErr) && netErr.Timeout() {
		setRelayCancelOrigin(c, constant2.RelayCancelOriginUpstreamTimeout)
	} else if errors.Is(err, context.Canceled) {
		setRelayCancelOrigin(c, constant2.RelayCancelOriginInternalAbort)
	}

	options := []types.NewAPIErrorOptions{
		types.ErrOptionWithHideErrMsg("upstream error: do request failed"),
	}
	isTimeoutFailure := errors.Is(err, context.DeadlineExceeded) || errors.As(err, &netErr) && netErr.Timeout()
	if isTimeoutFailure {
		phase := common2.GetContextKeyString(c, constant2.ContextKeyRelayTimeoutPhase)
		if phase == "connect" || phase == "tls_handshake" {
			phaseOptions := append([]types.NewAPIErrorOptions{}, options...)
			if requestMayHaveBeenSent {
				phaseOptions = append(phaseOptions, types.ErrOptionWithSkipRetry(), types.ErrOptionWithChannelPenalty())
			}
			errorCode := types.ErrorCodeUpstreamConnectionTimeout
			message := "upstream connection timed out"
			if phase == "tls_handshake" {
				errorCode = types.ErrorCodeUpstreamTLSHandshakeTimeout
				message = "upstream TLS handshake timed out"
			}
			return types.NewErrorWithStatusCode(
				errors.New(message),
				errorCode,
				http.StatusGatewayTimeout,
				phaseOptions...,
			)
		}
	}
	if requestMayHaveBeenSent {
		// Once any request write has completed or failed part-way through, a
		// timeout or connection error cannot prove that the provider rejected the
		// request. Retrying could duplicate a generation, task, tool call, or bill.
		options = append(options, types.ErrOptionWithSkipRetry(), types.ErrOptionWithChannelPenalty())
		if isTimeoutFailure {
			phase := common2.GetContextKeyString(c, constant2.ContextKeyRelayTimeoutPhase)
			if phase == "" {
				phase = "response_headers"
				common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutPhase, "response_headers")
				common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutSeconds, common2.RelayResponseHeaderTimeout)
			}
			errorCode := types.ErrorCodeUpstreamResponseHeaderTimeout
			message := "upstream response headers timed out before the first valid event"
			switch phase {
			case "connect":
				errorCode = types.ErrorCodeUpstreamConnectionTimeout
				message = "upstream connection timed out"
			case "tls_handshake":
				errorCode = types.ErrorCodeUpstreamTLSHandshakeTimeout
				message = "upstream TLS handshake timed out"
			case "request_write":
				errorCode = types.ErrorCodeUpstreamRequestWriteTimeout
				message = "upstream request write timed out after data may have been sent"
			}
			return types.NewErrorWithStatusCode(
				errors.New(message),
				errorCode,
				http.StatusGatewayTimeout,
				options...,
			)
		}
	}
	return types.NewError(err, types.ErrorCodeDoRequestFailed, options...)
}

func firstValidEventBudgetError(c *gin.Context, requestMayHaveBeenSent bool) *types.NewAPIError {
	setRelayCancelOrigin(c, constant2.RelayCancelOriginGatewayDeadline)
	common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutPhase, "first_valid_event_total")
	common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutSeconds, common2.RelayFirstEventTotalTimeout)
	options := []types.NewAPIErrorOptions{types.ErrOptionWithSkipRetry()}
	if requestMayHaveBeenSent {
		options = append(options, types.ErrOptionWithChannelPenalty())
	}
	return types.NewErrorWithStatusCode(
		errors.New("request-wide first valid event budget exhausted"),
		types.ErrorCodeUpstreamFirstEventTimeout,
		http.StatusGatewayTimeout,
		options...,
	)
}

// NewFirstValidEventTotalTimeoutError exposes the shared request-wide
// pre-output timeout to provider-specific WebSocket and SDK relay paths.
func NewFirstValidEventTotalTimeoutError(c *gin.Context, requestMayHaveBeenSent bool) *types.NewAPIError {
	return firstValidEventBudgetError(c, requestMayHaveBeenSent)
}

func nonStreamTotalTimeoutError(c *gin.Context, timeoutSeconds int, requestMayHaveBeenSent bool) *types.NewAPIError {
	setRelayCancelOrigin(c, constant2.RelayCancelOriginGatewayDeadline)
	common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutPhase, "non_stream_total")
	common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutSeconds, timeoutSeconds)
	options := []types.NewAPIErrorOptions{types.ErrOptionWithSkipRetry()}
	if requestMayHaveBeenSent {
		options = append(options, types.ErrOptionWithChannelPenalty())
	}
	return types.NewErrorWithStatusCode(
		errors.New("upstream non-stream response exceeded the total timeout"),
		types.ErrorCodeUpstreamNonStreamTimeout,
		http.StatusGatewayTimeout,
		options...,
	)
}

// NewNonStreamTotalTimeoutError exposes the shared non-stream timeout
// classification to provider-specific multi-step relay flows that continue
// after the initial HTTP response body has closed (for example task polling).
func NewNonStreamTotalTimeoutError(c *gin.Context, timeoutSeconds int, requestMayHaveBeenSent bool) *types.NewAPIError {
	return nonStreamTotalTimeoutError(c, timeoutSeconds, requestMayHaveBeenSent)
}

func setRelayCancelOrigin(c *gin.Context, origin string) {
	if c == nil || strings.TrimSpace(origin) == "" {
		return
	}
	common2.SetContextKey(c, constant2.ContextKeyRelayCancelOrigin, origin)
}

func doRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	common2.ResetRelayAttemptTimeoutContext(c)
	relayRequestStartedAt := time.Now()
	// Some provider adaptors build requests with their own timeout context before
	// delegating here. Preserve that deadline/value context while also binding it
	// to the inbound client lifetime. The combined context stays alive until the
	// response body is closed; canceling it on return from client.Do would truncate
	// every stream immediately after response headers.
	var combinedCancel context.CancelFunc
	var stopInbound func() bool
	nonStreamTimeout := 0
	nonStreamRemaining := time.Duration(0)
	var nonStreamTimer *cancelPhaseTimer
	var stopNonStreamObserver func() bool
	if req != nil && c != nil && c.Request != nil {
		// Carry the validated edge request ID through NewAPI and compatible
		// upstream relays (notably CPA) without overwriting an adaptor-provided
		// value. Providers that do not use this private X- header ignore it.
		if requestID := c.GetString(common2.RequestIdKey); requestID != "" {
			if req.Header.Get(common2.RequestIdKey) == "" {
				req.Header.Set(common2.RequestIdKey, requestID)
			}
			if req.Header.Get("X-Request-Id") == "" {
				req.Header.Set("X-Request-Id", requestID)
			}
		}
		var combinedCtx context.Context
		var cancel context.CancelFunc
		callerDeadline, hasCallerDeadline := req.Context().Deadline()
		if info != nil && !info.IsStream && common2.RelayNonStreamTimeout > 0 {
			configuredTimeout := time.Duration(common2.RelayNonStreamTimeout) * time.Second
			info.EnsureNonStreamDeadline(time.Time{}, configuredTimeout)
			remaining, limited := info.RemainingNonStreamBudget()
			if !limited {
				remaining = configuredTimeout
			}
			if remaining <= 0 {
				common2.ReleaseBodyAdmission(c)
				return nil, nonStreamTotalTimeoutError(c, common2.RelayNonStreamTimeout, false)
			}
			// A later job/provider envelope must not disable the precise local
			// request-wide budget. An earlier caller deadline still wins.
			if !hasCallerDeadline || time.Until(callerDeadline) > remaining {
				nonStreamTimeout = common2.RelayNonStreamTimeout
				nonStreamRemaining = remaining
			}
		}
		combinedCtx, cancel = context.WithCancel(req.Context())
		combinedCancel = cancel
		stopInbound = context.AfterFunc(c.Request.Context(), cancel)
		if nonStreamTimeout > 0 {
			nonStreamTimer = newCancelPhaseTimer(nonStreamRemaining, cancel)
			observedTimer := nonStreamTimer
			observedTimeout := nonStreamTimeout
			stopNonStreamObserver = context.AfterFunc(combinedCtx, func() {
				if observedTimer == nil || !observedTimer.Expired() || c.Request.Context().Err() != nil {
					return
				}
				setRelayCancelOrigin(c, constant2.RelayCancelOriginGatewayDeadline)
				common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutPhase, "non_stream_total")
				common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutSeconds, observedTimeout)
			})
		}
		req = req.WithContext(combinedCtx)
	}

	var client *http.Client
	var err error
	if info.ChannelSetting.Proxy != "" {
		client, err = service.GetHttpClientWithProxy(info.ChannelSetting.Proxy)
		if err != nil {
			if nonStreamTimer != nil {
				nonStreamTimer.Disarm()
			}
			if stopInbound != nil {
				stopInbound()
			}
			if combinedCancel != nil {
				combinedCancel()
			}
			return nil, fmt.Errorf("new proxy http client failed: %w", err)
		}
	} else {
		client = service.GetHttpClient()
	}

	// Do not set downstream SSE headers or write heartbeat bytes before the
	// upstream produces a valid event. Either action can commit a downstream 200
	// and hide an upstream first-event timeout from the controller.

	var requestMayHaveBeenSent atomic.Bool
	var transportPhase atomic.Int32
	const (
		transportPhaseUnknown int32 = iota
		transportPhaseConnect
		transportPhaseTLSHandshake
	)
	unsafeToReplay := !isReplaySafeMethod(req.Method)
	trace := &httptrace.ClientTrace{
		ConnectStart: func(_, _ string) {
			transportPhase.Store(transportPhaseConnect)
		},
		TLSHandshakeStart: func() {
			transportPhase.Store(transportPhaseTLSHandshake)
		},
		GotConn: func(httptrace.GotConnInfo) {
			transportPhase.Store(transportPhaseUnknown)
			common2.SetContextKey(c, constant2.ContextKeyRelayConnectedUpstream, true)
		},
		WroteRequest: func(wroteInfo httptrace.WroteRequestInfo) {
			if wroteInfo.Err == nil {
				common2.SetContextKey(c, constant2.ContextKeyRelayRequestWritten, true)
			} else {
				var writeNetErr net.Error
				if errors.Is(wroteInfo.Err, context.DeadlineExceeded) || errors.As(wroteInfo.Err, &writeNetErr) && writeNetErr.Timeout() {
					common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutPhase, "request_write")
				}
			}
			requestMayHaveBeenSent.Store(true)
			if unsafeToReplay {
				info.MarkUpstreamRequestMayHaveBeenAccepted()
			}
		},
	}
	req = req.WithContext(httptrace.WithClientTrace(req.Context(), trace))

	// The absolute pre-output budget is implemented with a stoppable cancel
	// timer rather than a Context deadline. Once response headers arrive the
	// timer is disarmed, allowing a healthy SSE body to continue indefinitely;
	// the scanner then uses the same deadline only until its first valid event.
	var budgetState atomic.Uint32 // 0=armed, 1=disarmed, 2=expired
	var budgetTimer *time.Timer
	if combinedCancel != nil {
		if remaining, limited := info.RemainingFirstValidEventBudget(); limited {
			if remaining <= 0 {
				if nonStreamTimer != nil {
					nonStreamTimer.Disarm()
				}
				if stopInbound != nil {
					stopInbound()
				}
				combinedCancel()
				return nil, firstValidEventBudgetError(c, false)
			}
			budgetTimer = time.AfterFunc(remaining, func() {
				if budgetState.CompareAndSwap(0, 2) {
					combinedCancel()
				}
			})
		}
	}

	// Task and provider-specific paths may not pass through controller.Relay's
	// validated DTO boundary. Release the parsing lease at the final outbound
	// boundary as an idempotent fallback, before waiting on response headers or
	// a potentially long-lived stream.
	common2.ReleaseBodyAdmission(c)
	resp, err := client.Do(req)
	if budgetTimer != nil {
		budgetState.CompareAndSwap(0, 1)
		budgetTimer.Stop()
	}
	requestReachedUpstream := requestMayHaveBeenSent.Load() || resp != nil
	unsafeRequestReachedUpstream := unsafeToReplay && requestReachedUpstream
	if unsafeRequestReachedUpstream {
		info.MarkUpstreamRequestMayHaveBeenAccepted()
	}
	if err != nil {
		var transportNetErr net.Error
		if !requestMayHaveBeenSent.Load() && (errors.Is(err, context.DeadlineExceeded) || errors.As(err, &transportNetErr) && transportNetErr.Timeout()) {
			switch transportPhase.Load() {
			case transportPhaseConnect:
				common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutPhase, "connect")
				common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutSeconds, common2.RelayDialTimeout)
			case transportPhaseTLSHandshake:
				common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutPhase, "tls_handshake")
				common2.SetContextKey(c, constant2.ContextKeyRelayTimeoutSeconds, common2.RelayTLSHandshakeTimeout)
			}
		}
		if nonStreamTimer != nil && nonStreamTimer.Expired() && (c == nil || c.Request == nil || c.Request.Context().Err() == nil) {
			if stopInbound != nil {
				stopInbound()
			}
			if resp != nil && resp.Body != nil {
				_ = resp.Body.Close()
			}
			return nil, nonStreamTotalTimeoutError(c, nonStreamTimeout, unsafeRequestReachedUpstream)
		}
		if nonStreamTimer != nil {
			nonStreamTimer.Disarm()
		}
		if stopInbound != nil {
			stopInbound()
		}
		if combinedCancel != nil {
			combinedCancel()
		}
		if budgetState.Load() == 2 && (c == nil || c.Request == nil || c.Request.Context().Err() == nil) {
			if resp != nil && resp.Body != nil {
				_ = resp.Body.Close()
			}
			return nil, firstValidEventBudgetError(c, unsafeRequestReachedUpstream)
		}
		classifiedErr := classifyDoRequestError(c, err, unsafeRequestReachedUpstream)
		if !types.IsSkipRetryError(classifiedErr) {
			logger.LogError(c, "do request failed: "+err.Error())
		}
		return nil, classifiedErr
	}
	if resp == nil {
		if nonStreamTimer != nil {
			nonStreamTimer.Disarm()
		}
		if stopInbound != nil {
			stopInbound()
		}
		if combinedCancel != nil {
			combinedCancel()
		}
		return nil, errors.New("resp is nil")
	}
	common2.SetContextKey(c, constant2.ContextKeyRelayResponseHeaders, true)
	if nonStreamTimer != nil && nonStreamTimer.Expired() {
		if resp.Body != nil {
			_ = resp.Body.Close()
		}
		if stopInbound != nil {
			stopInbound()
		}
		if combinedCancel != nil {
			combinedCancel()
		}
		if c != nil && c.Request != nil && c.Request.Context().Err() != nil {
			return nil, classifyDoRequestError(c, c.Request.Context().Err(), unsafeRequestReachedUpstream)
		}
		return nil, nonStreamTotalTimeoutError(c, nonStreamTimeout, unsafeRequestReachedUpstream)
	}
	if budgetState.Load() == 2 {
		if nonStreamTimer != nil {
			nonStreamTimer.Disarm()
		}
		if resp.Body != nil {
			_ = resp.Body.Close()
		}
		if stopInbound != nil {
			stopInbound()
		}
		if combinedCancel != nil {
			combinedCancel()
		}
		return nil, firstValidEventBudgetError(c, unsafeRequestReachedUpstream)
	}
	var streamErrorBodyTimer *cancelPhaseTimer
	if combinedCancel != nil && info.IsStream && (resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices) {
		if remaining, limited := info.RemainingFirstValidEventBudget(); limited {
			if remaining <= 0 {
				if resp.Body != nil {
					_ = resp.Body.Close()
				}
				if stopInbound != nil {
					stopInbound()
				}
				combinedCancel()
				return nil, firstValidEventBudgetError(c, unsafeRequestReachedUpstream)
			}
			// A stream's non-2xx response body is still pre-output error data. Keep
			// it inside the same request-wide first-event budget so a peer that
			// flushes only the error headers cannot outlive the outer proxy and turn
			// a gateway timeout into a downstream 499.
			streamErrorBodyTimer = newCancelPhaseTimer(remaining, combinedCancel)
		}
	}
	eventStreamResponse := isEventStreamContentType(resp.Header.Get("Content-Type"))
	if eventStreamResponse && info != nil && !info.IsStream {
		startTime := info.StartTime
		if startTime.IsZero() {
			startTime = relayRequestStartedAt
		}
		info.EnsureFirstValidEventDeadline(startTime, time.Duration(common2.RelayFirstEventTotalTimeout)*time.Second)
		if remaining, limited := info.RemainingFirstValidEventBudget(); limited && remaining <= 0 {
			if stopNonStreamObserver != nil {
				stopNonStreamObserver()
			}
			if nonStreamTimer != nil {
				nonStreamTimer.Disarm()
			}
			if resp.Body != nil {
				_ = resp.Body.Close()
			}
			if stopInbound != nil {
				stopInbound()
			}
			if combinedCancel != nil {
				combinedCancel()
			}
			return nil, firstValidEventBudgetError(c, unsafeRequestReachedUpstream)
		}
		info.IsStream = true
		common2.SetContextKey(c, constant2.ContextKeyIsStream, true)
	}
	if nonStreamTimer != nil && eventStreamResponse {
		// Some compatible providers ignore the request's stream flag and only
		// reveal SSE in the response headers. Once that happens, the non-stream
		// total budget must be removed; first-event and stream-idle guards own the
		// remaining lifecycle.
		if !nonStreamTimer.Disarm() {
			if stopNonStreamObserver != nil {
				stopNonStreamObserver()
			}
			if resp.Body != nil {
				_ = resp.Body.Close()
			}
			if stopInbound != nil {
				stopInbound()
			}
			if combinedCancel != nil {
				combinedCancel()
			}
			if c != nil && c.Request != nil && c.Request.Context().Err() != nil {
				return nil, classifyDoRequestError(c, c.Request.Context().Err(), unsafeRequestReachedUpstream)
			}
			return nil, nonStreamTotalTimeoutError(c, nonStreamTimeout, unsafeRequestReachedUpstream)
		}
		if stopNonStreamObserver != nil {
			stopNonStreamObserver()
			stopNonStreamObserver = nil
		}
		nonStreamTimer = nil
		nonStreamTimeout = 0
	}
	if combinedCancel != nil {
		if resp.Body == nil {
			if stopNonStreamObserver != nil {
				stopNonStreamObserver()
			}
			if nonStreamTimer != nil {
				nonStreamTimer.Disarm()
			}
			if streamErrorBodyTimer != nil {
				streamErrorBodyTimer.Disarm()
			}
			if stopInbound != nil {
				stopInbound()
			}
			combinedCancel()
		} else {
			resp.Body = &contextCancelReadCloser{
				ReadCloser:                   resp.Body,
				cancel:                       combinedCancel,
				stopInbound:                  stopInbound,
				requestCtx:                   req.Context(),
				ginCtx:                       c,
				nonStreamTimer:               nonStreamTimer,
				stopNonStreamObserver:        stopNonStreamObserver,
				nonStreamTimeout:             nonStreamTimeout,
				streamErrorBodyTimer:         streamErrorBodyTimer,
				unsafeRequestReachedUpstream: unsafeRequestReachedUpstream,
			}
		}
	}

	if upID := firstNonEmptyHeader(resp.Header, common2.RequestIdKey, "X-Request-Id", "OpenAI-Request-ID", "Request-ID"); upID != "" {
		c.Set(common2.UpstreamRequestIdKey, upID)
	}

	if req.Body != nil {
		_ = req.Body.Close()
	}
	if c != nil && c.Request != nil && c.Request.Body != nil {
		_ = c.Request.Body.Close()
	}
	return resp, nil
}

func isEventStreamContentType(contentType string) bool {
	return strings.HasPrefix(strings.ToLower(strings.TrimSpace(contentType)), "text/event-stream")
}

func firstNonEmptyHeader(header http.Header, names ...string) string {
	for _, name := range names {
		if value := strings.TrimSpace(header.Get(name)); value != "" {
			return value
		}
	}
	return ""
}

func isReplaySafeMethod(method string) bool {
	switch strings.ToUpper(strings.TrimSpace(method)) {
	case http.MethodGet, http.MethodHead, http.MethodOptions, http.MethodTrace:
		return true
	default:
		return false
	}
}

func DoTaskApiRequest(a TaskAdaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.BuildRequestURL(info)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	err = a.BuildRequestHeader(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}
